### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by cremacs** [mnp/dispwatch#1]
Hi, 

Thanks for this package - I've been looking for something like this for awhile. It would be good to see on MELPA, so there's my vote!

**Comment by zenspider** [comment]
Yes please. Happy to help.

**Comment by mnp** [comment]
In progress. https://github.com/melpa/melpa/pull/6315

**Comment by zenspider** [comment]
Hrm... I was about to submit a PR against dispwatch to make it so the hook run was argument-less (makes it easier to integrate into my system and the argument isn't that helpful tbh). Now that this is out there, I dunno... 

BTW, you might not benefit from it right now, but you might want to look at flycheck-package. It's pretty nice.

**Comment by mnp** [comment]
I'll look into flycheck-package, thanks.

About the hook arg, is it possible for you wrap with a lambda that discard the arg before calling your intended guy?  Ie something like 

     (add-hook 'dispwatch-display-change-hooks 
         (lambda (x) (my-real-hook)))

I'll share that my intention of passing the new resolution to the hook is so that the hook can make decisions based on what the new configuration is. I'd like to build on this package with another that remembers your current settings for each setup and uses this display hook to enact them.

**Comment by zenspider** [comment]
Totally. And that's basically what I've wrapped up here:

https://github.com/zenspider/elisp/blob/master/modes/dispwatch.el

But TBH, the old size is already in a variable, and the new size is available through a function call (and could be set to a variable as well) so the argument isn't saving that much.

**Comment by mnp** [comment]
True, maybe unnecessary future abstraction.  I'm happy to remove the arg before we go melpa, considering there's like, what, three of us.

**Comment by mnp** [comment]
And... we're on melpa.
