### ISSUE TITLE
DPI changes

### ISSUE THREAD

**Issue by vzaliva** [mnp/dispwatch#2]
I would like to use this script to change font size depending on monitor resolution. The problem is that I am interested in DPI, not in pixles. One can have 2 monitors with same number of pixels but different resolutions (e.g. if one is 15" and other is 17"). 

Is it possible to detect DPI change and trigger this hook as well?

Related discussion: https://emacs.stackexchange.com/questions/28390/quickly-adjusting-text-to-dpi-changes

**Comment by mnp** [comment]
Maybe, yeah. So there's two parts to think about here, detection and action.

The detection could look at all the values in `display-monitor-attributes-list`, which includes geometry, size, and name, and trigger if any have changed.  Not too hard, it would just trigger in more cases.

The action might be tricky: currently the hook gets `(W . H)` pixels. Option A would be to leave it as-is, and let the hook retrieve the extra attributes if it wanted them. I think this wouldn't be good for OP here, because they are switching on WH/XY, ie DPI. Option B would be to pass extra info to the hook, ie, `(X . Y)` size and display name.  That would not be backward compatible but would empower the hook to make more decisions. There's not too many users of this thing, but I hesitate to break their exiting state.

**Comment by vzaliva** [comment]
there is another solution. Keep current hook as-is but add another hook with extended parameters.

**Comment by vzaliva** [comment]
Meanwhile, I vote for "option A"

**Comment by mnp** [comment]
Agree. Have a try on this branch?  https://github.com/mnp/dispwatch/tree/feat/watch-more

**Comment by mnp** [comment]
I've given it a try on linux and windows. A typical display will look like `((name . "\\\\.\\DISPLAY1") (geometry 0 0 1920 1080) (mm-size 510 287) (workarea 0 0 1920 1050))` internally, and any changes there (which include DPI because it's geometry/mmsize) will trigger the current hook.

**Comment by vzaliva** [comment]
Looks great. Do you plan to update MELPA package soon?

**Comment by mnp** [comment]
Merged. Should get pulled by next melpa pull.

**Comment by zenspider** [comment]
Close? Also see #4 for similar issues wrt DPI changes.

**Comment by mnp** [comment]
Yep thx!
